name: square equation test


on:
  push:
    branches: ["spaceship1"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore Spaceship

      - name: Tests
        run: dotnet test /p:CollectCoverage=true
